version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '7432:5432'
    environment:
      POSTGRES_USER: project_next
      POSTGRES_DB: project_next
      POSTGRES_PASSWORD: project_next
